### ISSUE TITLE
Insecure dockerfiles

### ISSUE THREAD

**Issue by ugenef** [maxifom/urfu-abiturient#1]
Hey!
Thank you for your work, the site is pure gold and it looks even better than the official.
I`ve found one potential security issue at your dockerfiles.
https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b
By the way, why do you use the 2nd version of docker-compose at the prod .yml file?

**Comment by maxifom** [comment]
Hey. I use prod yml file for my production deployment, and the other one is for local. 
As for sexurity issue, personally I don't think this is much of an issue in my personal production environment, and because it's much simpler to write Dockerfile in this style and later to debug inside container, I stick with that approach. I find it particularly useful because if you run container as nonroot, there is no way to debug from inside the container (network issues, etc) without sudo.

**Comment by ugenef** [comment]
Catch ya, strong reasoning.
I usually use `docker exec -u 0` to enter the container as the root user, it works in all of my use cases (probably my use cases are pretty straightforward)
